schemaVersion: 2.0.0
fileExistenceTests:
  - name: 'accurate-scaler-otelcol-agent'
    path: '/home/app/bin/accurate-scaler-otelcol-agent'
    shouldExist: true
    permissions: '-rwxr-xr-x'
  - name: 'accurate-scaler.sh'
    path: '/home/app/.profile.d/accurate-scaler.sh'
    shouldExist: true
    permissions: '-rwxr-xr-x'
  - name: 'otelcol-agent-config.yaml'
    path: '/home/app/accurate-scaler/otelcol-agent-config.yaml'
    shouldExist: true
    permissions: '-rw-r--r--'
